#!/bin/bash
clear

PLAYLIST="%(extractor)s/playlists/%(playlist_title)s/%(uploader)s_%(channel_id)s - %(title)s [%(id)s].%(ext)s"
CHANNEL="%(extractor)s/%(uploader)s_%(channel_id)s/%(title)s [%(id)s].%(ext)s"
WEB="%(extractor)s/%(title)s [%(id)s].%(ext)s"

if [[ "$1" =~ ^.*youtu.*$ ]] || [[ "$1" =~ ^.*youtube.*$ ]]; then
    echo -e "Downloading video...\\n> URL: ${1}\\n"
    if [[ "$1" =~ .*/playlist.* ]] || [[ "$1" =~ .*list=.* ]]; then
        opt="$PLAYLIST"
        echo "Playlist detected"
    else
        opt="$CHANNEL"
        echo "Channel detected"
    fi
    yt-dlp -o "/sdcard/Download/$opt" -f 'bestvideo[ext=mkv]+bestaudio[ext=m4a]/best[ext=mkv]/best' --embed-subs --sub-lang en --add-metadata --embed-thumbnail --user-agent "Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0" "$1"
elif [[ "$1" =~ ^http.*$ ]]; then
    echo -e "Downloading video...\\n> URL: ${1}\\n"
    opt="$WEB"
    echo "Web address detected"
    yt-dlp -o "/sdcard/Download/$opt" -f 'bestvideo[ext=mkv]+bestaudio[ext=m4a]/best[ext=mkv]/bestaudio[ext=m4a]/best' --add-metadata --embed-thumbnail --user-agent "Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0" "$1"
else
    echo "Error: No URL provided"
fi
